### ISSUE TITLE
Parallelize the MCMC sampler?

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow2#202]
This is a feature of `psborrow` but not `psborrow2`.

**Comment by gravesti** [comment]
I've had a look at this and found some opportunities:

- in cmdstanr's sample there is the argument `parallel_chains = getOption("mc.cores", 1)`, so our users could directly specify this via `mcmc_sample(..., parallel_chains = 4)` or set the option eg `options('mc.cores' = 4)`
- use `foreach` or `futures` constructions in `mcmc_sample` for simulation objects. The user could then register their favourite backend for parallel processing of simulations, locally or across nodes. 

The user would have to pay attention that they don't over allocate cores if they use both approaches on a single machine.

**Comment by gravesti** [comment]
One challenge will be if we need to save the models and the draws files it they are on different nodes.

**Comment by gravesti** [comment]
@mattsecrest  separately from this investigation into `future`, I propose that we explicitly add the `parallel_chains` argument to `mcmc_sample()`
