### ISSUE TITLE
design for data simulation

### ISSUE THREAD

**Issue by gravesti** [Genentech/psborrow2#210]
### Feature description

Functions to simulate data as in psborrow

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

**Comment by mattsecrest** [comment]
@gravesti I think this looks great! I have two questions.

1. I don't see anywhere where we easily add multiple iterations to a given simulation scenario. Am I missing somehting or will the user just do this themselves?
2. I am not sure about accomodating `I(age^2)` in the model formula or instead giving the user access to the simulatd data to make their own changes, eg:

```
baseline_obj <- sim_baseline(
  sample_size = c(trt_int = 100, ctrl_int = 50, ctrl_ext = 200),
  covariates = list(correlated_covs, indep_covs)
) %>% 
  add_vars(age_2 = age*age)
```
