### ISSUE TITLE
Pare down CI/CD pipeline?

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow2#233]
@gravesti @danielinteractive just wanted to brainstorm paring down the CI/CD pipeline for `psborrow2`. Definitely I appreciate the efforts to make the pipeline robust and industry-leading, but I suspect it is more complex than we truly need. One concern for me is that it is updated asynchronously with `psborrow2`, so we have had instances where the pipeline succeeds or fails for the same commit for reasons that are opaque to us. As another concern, just today my pre-commit was off and I forgot to style and discovered that it will style and commit to your branch for you. I wonder if that is necessary for an open-source package that is intended to bring developers together...? In this particular case, it also looks like the automatic `styler` updates appear to conflict with the `lintr`.

Even in the absence of specific issues, I wonder what the minimal CI/CD set we need is? I was thinking we need to have just two:
- R CMD CHECK
- Code coverage
Anything else? I think the rest we can handle with good coding practices and a nice developer guide. If a `styler` call gets missed once in a blue moon, I would argue it's not the end of the world.

**Comment by danielinteractive** [comment]
Thanks @mattsecrest for bringing up the discussion topic. 

Well... I would leave this to the package maintainer to ultimately decide - i.e. I don't want to force anything here. However, I would recommend weighing in the benefits we have from using the standard pipeline (in particular, we don't need to worry too much about it ourselves, get automatic updates for it and can involve the IDR team when anything comes up).

**Comment by mattsecrest** [comment]
Thanks for the input @danielinteractive . Let me propose some changes in a PR and we can discuss. Would also be curious what @gravesti thinks on this one

**Comment by gravesti** [comment]
I'm sympathetic to your points @mattsecrest, especially about the frustrations with lintr and styler disagreeing.
I think we should turn off the automatic committing by the CI checks (styler, roxygen), however I think there's value in having the checks there.
I would advocate for at least roxygen, lintr, and spell check, even if they are not required for merges.
From past experience, it's much easier to maintain good spelling/style on each commit than to go through and fix it again.

**Comment by gravesti** [comment]
To add to your minimal list:

- build pkgdown site

**Comment by mattsecrest** [comment]
Closed with #235
