### ISSUE TITLE
Bringing back data simulating functions from psborrow

### ISSUE THREAD

**Issue by zhiiiyang** [Genentech/psborrow2#238]
Hi @Kat-Jump and I wonder if it possible to bring back some data simulating functions that take more parameters in simulating the data (ie, enrollment, dropout, etc). Those functions are taken from the [vignette](https://genentech.github.io/psborrow/articles/user_guide.html) of psborrow. 

[set_n](https://genentech.github.io/psborrow/reference/set_n.html)
[set_cov](https://genentech.github.io/psborrow/reference/set_cov.html)
[simu_cov](https://genentech.github.io/psborrow/reference/simu_cov.html)
[set_event](https://genentech.github.io/psborrow/reference/set_event.html)
[set_clin](https://genentech.github.io/psborrow/reference/set_clin.html)
[simu_time](https://genentech.github.io/psborrow/reference/simu_time.html)

**Comment by zhiiiyang** [comment]
Hi thank you for recreating the old data simulating functions. I have a follow-question regarding the `data_matrix_list` argument in `create_simulation_obj` function. 

Normally, `data_matrix_list` will take in something like below 

```
SimDataList object with  4  different scenarios
  true_hr          drift_hr id n_datasets_per_param
1     0.6       No drift HR  1                   10
2     1.0       No drift HR  2                   10
3     0.6 Moderate drift HR  3                   10
4     1.0 Moderate drift HR  4                   10
```

However, in your recent example vignette, it has become the following. (I believe `treatment_effect` might be in the linear scale now).
```
SimDataList object with  2  different scenarios
  sim_id treatment_effect drift n_datasets_per_param
1      1                1     0                    3
2      2                1     1                    3
```

Is it possible to keep these two consistent by using the HR instead? If not, it will be better to specify how to convert `true_hr` and `drift_hr` to `treatment_effect` and `drift`. 

Thanks, 
Zhi

**Comment by gravesti** [comment]
@zhiiiyang Yes, this is indeed inconsistent. 
Do you think it's ok that the other covariates are specified on the linear predicator scale and drift and treatment are on the HR scale? (This is how it was in psborrow). Currently all are specified on the log scale, since they all become betas in the survival simulation model.
@mattsecrest  Any thoughts?

**Comment by zhiiiyang** [comment]
Yes, maybe we can change the following lines of codes below to take in HR values instead? 
https://github.com/Genentech/psborrow2/blob/de4f717eac0bb576929341ba285fa4e831174015/R/simulate_data.R#L505-L506


> @zhiiiyang Yes, this is indeed inconsistent. Do you think it's ok that the other covariates are specified on the linear predicator scale and drift and treatment are on the HR scale? (This is how it was in psborrow). Currently all are specified on the log scale, since they all become betas in the survival simulation model. @mattsecrest Any thoughts?

**Comment by gravesti** [comment]
@zhiiiyang I have changed the code to take hazard ratios instead in the latest commit on this branch. The new arguments to the functions are `treatment_hr` and `drift_hr`.

**Comment by zhiiiyang** [comment]
@gravesti Thank you! Will take a look. There a few mores minor places that need might updating. 
For the vignette, https://github.com/Genentech/psborrow2/blob/238-data-simulation/vignettes/original/_data_simulation.Rmd

1. change `treatment_effect` to `treatment_hr` in line 147, 158
2. change `drift_hr = c(0, 1)` to `drift_hr = c(0, 1)` in line 252
3. also getting an error message running line 334
![image](https://github.com/Genentech/psborrow2/assets/7269113/5ac1e795-190c-4ea4-9384-274215e8dc04)
4. I noticed that you only change `vignettes/original/_data_simulation.Rmd`. Are you also gonna change `vignettes/data_simulation.Rmd`?

**Comment by mattsecrest** [comment]
Thanks @zhiiiyang  for your suggestions! These functions have been added to the `main` branch if you would like to test them out.
