### ISSUE TITLE
Normal outcomes

### ISSUE THREAD

**Issue by gravesti** [Genentech/psborrow2#248]
Can we implement continuous normal outcomes?

- [x] Define continuous outcome parent class
- [x] Define ContinuousNormalOutcome
  - [x] continuous_var
  - [x] prior on sigma

**Comment by gravesti** [comment]
Some code to test. The example data is probably very unsuitable, but it demonstrates the mechanics of setting up some models.

```r

# Set up a continuous normal outcome
om <- outcome_cont_normal(continuous_var = "time", baseline_prior = prior_normal(0, 100), std_dev_prior = prior_half_cauchy(1, 5))

# Full Borrowing
result_full <- mcmc_sample(
  create_analysis_obj(
    data_matrix = example_matrix,
    outcome = om,
    borrowing = borrowing_details("Full borrowing", "ext"),
    treatment = treatment_details("trt", prior_normal(0, 10000)),
    covariates = add_covariates(c("cov1", "cov2"), priors = prior_normal(0, 100)),
    quiet = TRUE
  ),
  seed = 123, parallel_chains = 4
)
result_full
lm_full <- lm(time ~ trt + cov1 + cov2, data = as.data.frame(example_matrix))
summary(lm_full)


# No Borrowing
result_none <- mcmc_sample(
  create_analysis_obj(
    data_matrix = example_matrix,
    outcome = om,
    borrowing = borrowing_details("No borrowing", "ext"),
    treatment = treatment_details("trt", prior_normal(0, 10000)),
    covariates = add_covariates(c("cov1", "cov2"), priors = prior_normal(0, 100)),
    quiet = TRUE
  ),
  seed = 123, parallel_chains = 4
)
result_none
lm_none <- lm(time ~ trt + cov1 + cov2, data = as.data.frame(example_matrix), subset = example_matrix[, "ext"] == 0)
summary(lm_none)

# Hierarchical Dynamic Borrowing
result_bdb <- mcmc_sample(
  create_analysis_obj(
    data_matrix = example_matrix,
    outcome = om,
    borrowing = borrowing_details("BDB", "ext", prior_gamma(0.01, 0.01)),
    treatment = treatment_details("trt", prior_normal(0, 10000)),
    covariates = add_covariates(c("cov1", "cov2"), priors = prior_normal(0, 100)),
    quiet = TRUE
  ),
  seed = 123, parallel_chains = 4
)
result_bdb

# Fixed Weight Borrowing
result_50 <- mcmc_sample(
  create_analysis_obj(
    data_matrix = cbind(example_matrix, w = 0.5),
    outcome = outcome_cont_normal(continuous_var = "time", baseline_prior = prior_normal(0, 100), std_dev_prior = prior_half_cauchy(1, 5), weight_var = "w"),
    borrowing = borrowing_details("Full borrowing", "ext"),
    treatment = treatment_details("trt", prior_normal(0, 10000)),
    covariates = add_covariates(c("cov1", "cov2"), priors = prior_normal(0, 100)),
    quiet = TRUE
  ),
  seed = 123, parallel_chains = 4
)
result_50
lm_50 <- lm(time ~ trt + cov1 + cov2, data = as.data.frame(example_matrix), weights = rep(0.5, nrow(example_matrix)))
summary(lm_50)



# BayesPPD Fixed Power Parameters
library('BayesPPD')

set.seed(123)
normal_ppd_reslist <- lapply(c(0, 0.25, 0.5, 0.75, 1), function(w) {
  normal_ppd <- glm.fixed.a0(
    data.type = "Normal",
    y = example_matrix[example_matrix[, "ext"] == 0, ][, "time"],
    x = example_matrix[example_matrix[, "ext"] == 0, ][, c("trt", "cov1", "cov2")],
    historical = list(list(
      y0 = example_matrix[example_matrix[, "ext"] == 1, ][, "time"],
      x0 = example_matrix[example_matrix[, "ext"] == 1, ][, c("cov1", "cov2")],
      a0 = w
    )),
    lower.limits = rep(-100, 5),
    upper.limits = rep(100, 5),
    slice.widths = rep(1, 5),
    nMC = 10000,
    nBI = 1000
  )[[1]][[1]]
  ci <- apply(normal_ppd, 2, quantile, probs = c(0.025, 0.975))
  data.frame(
    fitter = "BayesPPD",
    borrowing = w,
    variable = c("(Intercept)", "trt", "cov1", "cov2"),
    estimate = colMeans(normal_ppd),
    lower = ci[1, ],
    upper = ci[2, ]
  )
})


# Random Power Parameter
random_powerprior <- glm.random.a0(
  data.type = "Normal",
  y = example_matrix[example_matrix[, "ext"] == 0, ][, "time"],
  x = example_matrix[example_matrix[, "ext"] == 0, ][, c("trt", "cov1", "cov2")],
  historical = list(list(
    y0 = example_matrix[example_matrix[, "ext"] == 1, ][, "time"],
    x0 = example_matrix[example_matrix[, "ext"] == 1, ][, c("cov1", "cov2")],
    a0 = w
  )),
  lower.limits = rep(-100, 5),
  upper.limits = rep(100, 5),
  slice.widths = rep(1, 5),
  nMC = 10000,
  nBI = 1000
)
random_ci <- apply(random_powerprior[[1]][[1]], 2, quantile, probs = c(0.025, 0.975))

# Borrowing is the posterior mean of the power parameter
data.frame(
  fitter = "BayesPPD",
  borrowing = mean(random_powerprior$posterior.samples$`posterior samples of a0`),
  variable = c("(Intercept)", "trt", "cov1", "cov2"),
  estimate = colMeans(random_powerprior[[1]][[1]]),
  lower = random_ci[1, ],
  upper = random_ci[2, ]
)
```

**Comment by aaschenbrenner** [comment]
During installation of development version, I get an error 404:

> remotes::install_github("genentech/psborrow2", "248-normal-outcomes") #development version with normal outcomes
Downloading GitHub repo genentech/psborrow2@248-normal-outcomes
curl: (22) The requested URL returned error: 404 
Error in utils::download.file(url, path, method = "curl", quiet = quiet,  : 
  'curl' call had nonzero exit status

 sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  tcltk     methods  
[8] base     

other attached packages:
[1] tcltk2_1.2-11

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.11       urlchecker_1.0.1  compiler_4.2.3    later_1.3.1      
 [5] remotes_2.4.2.1   prettyunits_1.2.0 profvis_0.3.8     tools_4.2.3      
 [9] digest_0.6.33     pkgbuild_1.4.2    pkgload_1.3.3     jsonlite_1.8.7   
[13] memoise_2.0.1     lifecycle_1.0.4   rlang_1.1.2       shiny_1.7.5.1    
[17] cli_3.6.1         rstudioapi_0.15.0 curl_5.1.0        fastmap_1.1.1    
[21] httr_1.4.7        stringr_1.5.1     vctrs_0.6.4       fs_1.6.3         
[25] htmlwidgets_1.6.2 devtools_2.4.5    glue_1.6.2        R6_2.5.1         
[29] processx_3.8.2    sessioninfo_1.2.2 callr_3.7.3       purrr_1.0.2      
[33] magrittr_2.0.3    usethis_2.2.2     promises_1.2.1    ps_1.7.5         
[37] ellipsis_0.3.2    htmltools_0.5.7   mime_0.12         xtable_1.8-4     
[41] httpuv_1.6.12     stringi_1.8.1     miniUI_0.1.1.1    cachem_1.0.8     
[45] crayon_1.5.2

**Comment by gravesti** [comment]
@aaschenbrenner We merged these changes into the main branch now, so you can install with just
`remotes::install_github("genentech/psborrow2")`

**Comment by aaschenbrenner** [comment]
@gravesti thanks it works now!

**Comment by Teniola17** [comment]
I tried the Bayesian Dynamic Borrowing using a data matrix shown beneath
         outcome group hist         cov1         cov2
1   -0.040830234     0    0  1.249974599  0.407272592
2    2.990811877     0    0  0.647482052 -0.115168802
3   -1.912042389     0    0 -1.559541453 -1.271328363
4    0.055043906     0    0  0.111360544 -0.022077709
5    0.534520353     0    0 -0.257908961  0.322214162
6   -1.648723770     0    0 -1.776434427 -1.455024514
7   -1.101525872     0    0 -0.693858173  0.021134959
The outcome object specification code is as follows:

```
 norm <- outcome_cont_normal(
  continuous_var = "outcome",
  baseline_prior = prior_normal(0, 100),
  std_dev_prior = prior_half_cauchy(1, 5)
)



borrowing <- borrowing_hierarchical_commensurate(
  ext_flag_col = "hist",
  tau_prior = prior_gamma(0.001, 0.001)
)
```



I got the error message below:



```
Semantic error in 'C:/Users/EMMANU~1/AppData/Local/Temp/Rtmpwvu0mv/model-73fcc9a69fd.stan', line 31, column 2 to column 10:
   -------------------------------------------------
    29:    beta_trt ~ normal(0, 1000) ;
    30:    
    31:    alpha[2] ~ normal(0, 100) ;
           ^
    32:    std_dev_outcome ~ cauchy(1, 5) ;
    33:  
   -------------------------------------------------

Tried to index a scalar type. Expression has type real.
```


Pls where am I going wrong?
