### ISSUE TITLE
rename_draws_covariates() does not work with continuous outcome

### ISSUE THREAD

**Issue by xiaoli-mcw** [Genentech/psborrow2#310]
Hi, I was trying to use psborrow2 for a continuous outcome. But I got an error message about rename_draws_covariates() function. I suspect it is related to the variable_dictionary() function, which returns two different descriptions for the same beta_trt Stan variable. Attached is the test code that I used.
Thank you!

<img width="460" alt="Screenshot 2024-12-16 105717" src="https://github.com/user-attachments/assets/d0c8e4d5-0dc7-48ec-a398-8cf4d9fedd58" />
[Continuous_issue.txt](https://github.com/user-attachments/files/18155335/Continuous_issue.txt)

**Comment by gravesti** [comment]
Thanks for the report @xiaoli-mcw 
I will look into it

**Comment by gravesti** [comment]
Hi @xiaoli-mcw 
I have fixed this in a branch, which you can try by installing with the command below. Let me know if that works for you.

```r
remotes::install_github("Genentech/psborrow2", ref = "310-rename_draws_covariates-does-not-work-with-continuous-outcome")
```

Probably this fix will not be merged until January.

**Comment by xiaoli-mcw** [comment]
It works for me. Thank you @gravesti
