### ISSUE TITLE
Should we clean up / return the Stan model string?

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow2#63]
@gravesti , as I wrap up the Stan model text, I wonder if we need to do anything to prettify the model string. I played around with this a bit, but it was surprisingly hard to get the formatting correct given the variable inputs. Anyways, I do not think we need to give the stan model string to the user, so I don't think it matters greatly, but want to check with you as well!

**Comment by gravesti** [comment]
I think it's ok as is. We can also address this directly in the refactoring of the model string preparation in #113
