### ISSUE TITLE
consider moving covariates to last argument of `create_analysis_obj` to make it easier to specify arguments positionally

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow2#93]
Regarding `create_analysis_object()` https://github.com/Genentech/psborrow2/blob/e941cae1dc283990661c5b35763891f72920f0b0/R/create_analysis_obj.R#LL46C1-L51C47

Could we change the definition to this?

```r
create_analysis_obj <- function(data_matrix,
                                outcome,
                                borrowing,
                                treatment,
                                covariates = NULL,
                                quiet = FALSE)
```

Currently it is 
```r
create_analysis_obj <- function(data_matrix,
                                covariates = NULL,
                                outcome,
                                borrowing,
                                treatment,
                                quiet = FALSE)
```

The benefit would be that we can more easily write
`create_analysis_object(my_data, weibull_outcome, weak_borrowing, trt_obj)` since `covariates` is an optional argument.

Steps:

- [ ] Change order of arguments
- [ ] Check if any functions which call `create_analysis_object()` need to be updated
- [ ] Updates examples
- [ ] Confirm tests and checks pass

**Comment by gravesti** [comment]
@LeiShi-rocks This might be a good one to try. It's a simple change but is good practice for working with git and package checks/tests etc

**Comment by LeiShi-rocks** [comment]
Thanks Issac! I will start digging from here : )

**Comment by LeiShi-rocks** [comment]
> @LeiShi-rocks This might be a good one to try. It's a simple change but is good practice for working with git and package checks/tests etc

Thanks Issac! I will start digging from here : )

**Comment by LeiShi-rocks** [comment]
Hi Matt and Issac, I have finished this task using the searching feature of Github, which helps a big time by showing all places that `create_analysis_object()` appear. Mostly it shows up in the example part of the roxygen comments so I also updated the examples. Also the test files run smoothly. So should be good to go : )

I can show you the edits later. Is there a way to create a new branch and push updates into the repo? Seems that I don't have the permission. Thanks!

**Comment by mattsecrest** [comment]
Hi @LeiShi-rocks , so sorry we missed this. I personally was on vacation this week. If you're interested in contributing, we'd happily schedule a quick meeting and go over some useful first issues. I'm cleaning up at the moment and will remove this particular one. Thanks!

**Comment by mattsecrest** [comment]
Actually we may as well implement and close in #254
